steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/buysell-backend-huex', '.' ]
# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=asia.gcr.io/$PROJECT_ID/cupet-backend
#   - --cache=true
#   - --cache-ttl=6h  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/buysell-backend-huex']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', 'buysell-backend-huex','--max-instances', '3', '--memory', '1000Mi', '--image', 'asia.gcr.io/$PROJECT_ID/buysell-backend-huex', '--region', 'us-west2', '--platform', 'managed', '--allow-unauthenticated', '--vpc-connector', 'hu-conn', '--add-cloudsql-instances', 'mysql-hu', '--set-env-vars', 'DBN=buysellapphuex']
logsBucket: 'gs://us-gcp-ame-con-116-npd-1_cloudbuild/buysell'
